accounts/urls.py
from django.urls import path
from .views import signin, signup, profile, logout

app_name = 'accounts'
urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name="logout")
]

pages/urls.py
from django.urls import path
from .views import home, about, coffee

app_name = 'pages'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('coffee/', coffee, name='coffee'),
]

products/urls.py
from django.urls import path, include
from .views import ProductList, filter, ProductDetail, search

app_name = 'products'
urlpatterns = [
    path('', ProductList.as_view(), name='product-list'),
    path('s/', filter, name='filter'),
    path('<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('search/', search, name='search'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='index')),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/pretty-checkbox.min.css' %}">
    <title>My Coffee{% block title %}{% endblock%}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <a class="navbar-brand" href="{% url 'pages:home' %}">
            <img src="{% static 'img/mycoffee.png' %}" class="img-brand" alt="My Coffee">
            My Coffee
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

              <li
               {% if request.path == "/" %}
                class="nav-item active"
               {% else %}
                class="nav-item"
               {% endif %}
              >
                  <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
              </li>

              <li 
              {% if 'signin' in request.path or 'signup' in request.path or 'profile' in request.path %}
                class="nav-item dropdown active"
              {% else %}
                class="nav-item dropdown"
              {% endif %}
              >
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if request.user.is_authenticated %}
                  Welcome
                {% else %}
                  Join us
                {% endif %}
                </a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
                {% if request.user.is_authenticated %}
                  <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile({{request.user.username}})</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                {% else %}
                  <a class="dropdown-item" href="{% url 'accounts:signin' %}">Sign in</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign up</a>
                {% endif %}
                </div>
              </li>

              <li 
              {% if 'coffee' in request.path %}
                class="nav-item active"
              {% else %}
                class="nav-item"
              {% endif %}
              id="coffee-nav-item">
                  <a class="nav-link" href="{% url 'pages:coffee' %}">Coffee</a>
              </li>

              <li 
              {% if 'product' in request.path or 'search' in request.path %}
                class="nav-item dropdown active"
              {% else %}
                class="nav-item dropdown"
              {% endif %}
              >
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Products
                </a>
                <div class="dropdown-menu animate slideIn" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Drinks</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Food</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'products:product-list' %}">All Products</a>
                </div>
              </li>

              <li 
              {% if 'about' in request.path %}
                class="nav-item active"
              {% else %}
                class="nav-item"
              {% endif %}
              >
                <a class="nav-link" href="{% url 'pages:about' %}">About</a>
              </li>

            </ul>
            {% if request.user.ia_authenticated %}
            <!--
              <span class="text-light" style="margin-right: 5px">
                Welcome, {{request.user.username}}
              </span>
            -->
            {% endif %}
            <form action="{% url 'products:filter' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2 remove-outline" name="sname" type="search" placeholder="Search" aria-label="Search">
            <div class="btn-group" role="group">
              <button class="btn btn-warning my-2 my-sm-0" type="submit">Search</button>
              <a title="Advanced Search" data-toggle="tooltip" href="{% url 'products:search' %}" class="btn btn-warning my-2 my-sm-0" type="submit">
                <svg class="bi bi-gear" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"/>
                  <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
                </svg>
              </a>
            </div>
            
            </form>
        </div>
    </nav>


{% block body %}
{% endblock body %}

    <footer class="pt-4 navbar-custom text-light">
      <div class="container-fluid text-center text-md-left">

        <div class="row">

          <div class="col-md-6 mt-md-0 mt-3">
            <h5 class="text-uppercase">
              <img src="{% static 'img/mycoffee.png' %}" class="img-brand" alt="My Coffee">
              My Coffee
            </h5>
            <p>Order your favorite coffee, and get it wherever you are.</p>
          </div>

          <hr class="clearfix w-100 d-md-none pb-3">

          <div class="col-md-3 mb-md-0 mb-3">

            <h5 class="text-uppercase">Delivery Service</h5>

            <ul class="list-unstyled">
              <li><a href="tel:333333333">333-333-333</a></li>
              <li><a href="tel:444333332">444-333-332</a></li>
              <li><a href="tel:555333331">555-333-331</a></li>
              <li><a href="tel:666333333">666-333-333</a></li>
            </ul>

          </div>

          <div class="col-md-3 mb-md-0 mb-3">

            <h5 class="text-uppercase">Join Us</h5>

            <ul class="list-unstyled">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">YouTube</a></li>
              <li><a href="#">Twitter</a></li>
            </ul>

          </div>

        </div>

      </div>

      <div class="text-center py-3">
        Copyright &copy; <span class="year">2019</span> My Coffee. Powered By Hassouna Academy
      </div>

    </footer>

    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })
        $(".year").text( (new Date).getFullYear() );
    </script>
    <script type="text/javascript">
      $('[data-toggle="tooltip"]').tooltip();
    </script>
  </body>
</html>

templates/msgs.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
        <strong>
            {% if 'danger' == msg.tags %}
                Error
            {% else %}
                {{msg.tags|title}}
            {% endif %}
        </strong>: {{msg}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>
    {% endfor %}
{% endif %}