pages/urls.py
from django.urls import path
from .views import home, about, coffee

app_name = 'pages'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('coffee/', coffee, name='coffee'),
]

products/urls.py
from django.urls import path, include
from .views import ProductList, filter, ProductDetail, search

app_name = 'products'
urlpatterns = [
    path('', ProductList.as_view(), name='product-list'),
    path('s/', filter, name='filter'),
    path('<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('search/', search, name='search'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='index')),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.utils import timezone

FLAG_OPTION = (
    ('Hot Coffee', 'Hot Coffee'),
    ('Hot Tea', 'Hot Tea'),
    ('Hot Drink', 'Hot Drink'),
    ('Cold Coffee', 'Cold Coffee'),
    ('Iced Tea', 'Iced Tea'),
    ('Cold Drink', 'Cold Drink'),
    ('Hot Breakfast', 'Hot Breakfast'),
    ('Bakery', 'Bakery'),
    ('Lunch', 'Lunch'),
    ('Snacks&Sweets', 'Snacks&Sweets'),
)

class Product(models.Model):
    name = models.CharField(max_length=120)
    desc = models.TextField(max_length=10000)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    is_active = models.BooleanField(default=True)
    publish_date = models.DateTimeField(default=timezone.now)
    flag = models.CharField(max_length=20, choices=FLAG_OPTION)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-publish_date']

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product

class ProductList(ListView):
    model = Product

class ProductDetail(DetailView):
    model = Product
    
def search(request):
    return render(request, 'products/search.html')

def filter(request):
    products = Product.objects.all()
    name = None
    desc = None
    sfrom = None
    sto = None
    sensitive = None
    if 'sensitive' in request.GET:
        sensitive = request.GET['sensitive']
        if not sensitive:
            sensitive = 'off'
            
    if 'sname' in request.GET:
        name = request.GET['sname']
        if name:
            if sensitive == 'on':
                products = products.filter(name__contains=name)
            else:
                products = products.filter(name__icontains=name)
                
    if 'sdescription' in request.GET:
        desc = request.GET['sdescription']
        if desc:
            if sensitive == 'on':
                products = products.filter(desc__contains=desc)
            else:
                products = products.filter(desc__icontains=desc)
            
    if 'sfrom' in request.GET and 'sto' in request.GET:
        sfrom = request.GET['sfrom']
        sto = request.GET['sto']
        if sfrom and sto:
            if sfrom.isdigit() and sto.isdigit():
                products = products.filter(price__gte=sfrom, price__lte=sto)
    context={
        'products':products
    }
    return render(request, 'products/product_filter.html', context)

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %} | Product Details{% endblock%}
{% block body %}
    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form>
            <h2 class="text-center">Product Details</h2>
            <hr>

            <section>
                
                  <div class="row p-5 " >

                    <div class="card mb-3 w-100" >
                      <div class="row no-gutters">
                        <div class="col-md-4">

                            <div class="details-label-group">
                                <label class="details-label new">{{product.flag}}</label>
                            </div>
                            <img src="{{product.image.url}}" class="card-img" alt="...">
                            
                        </div>
                        <div class="col-md-8">
                          <div class="card-body">
                            <h5 class="card-title" id="productName">{{product}}</h5>
                            <hr>
                            <p class="card-text" id="description">{{product.desc}}</p>
                            <hr>
                            <p class="card-text">Current Price: <span id="price" class="bg-dark text-light rounded-circle p-2">${{product.price}}</span></p>
                            <hr>
                            <button type="submit" class="btn btn-warning">Add To Cart</button>
                            <button type="submit" class="btn btn-warning text-white">
                              <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                              </svg>
                            </button>
                            <hr>
                            <a href="{% url 'products:product-list' %}" class="btn btn-warning" >All Products</a>
                            <a href="{% url 'pages:home' %}" class="btn btn-warning text-white" >
                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                              </svg>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                
            </section>
        

        </form>

    </div>
{% endblock body %}

products/templates/products/product_filter.html
{% extends 'base.html' %}

{% block title %} | Products{% endblock%}
{% block body %}
    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form>
            <h2 class="text-center">Products</h2>
            <hr>

            <section>
                <div class="container-fluid">
                  <div class="row p-5" >
                    {% for product in products %}
                    <div>
                      <div class="card m-2" style="width: 18rem;">
                        <div class="details-label-group">
                          <label class="details-label new">{{product.flag}}</label>
                        </div>
                        <img src="{{product.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{product}}</h5>
                          <p class="card-text">{{product.desc}}.</p>
                          <a href="{% url 'products:product-detail' product.id %}" class="btn btn-warning">Show Details</a>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
            </section>
        

        </form>

    </div>
{% endblock body %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %} | Products{% endblock%}
{% block body %}
    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form>
            <h2 class="text-center">Products</h2>
            <hr>

            <section>
                <div class="container-fluid">
                  <div class="row p-5" >
                    {% for product in product_list %}
                    <div>
                      <div class="card m-2" style="width: 18rem;">
                        <div class="details-label-group">
                          <label class="details-label new">{{product.flag}}</label>
                        </div>
                        <img src="{{product.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{product}}</h5>
                          <p class="card-text">{{product.desc}}.</p>
                          <a href="{% url 'products:product-detail' product.id %}" class="btn btn-warning">Show Details</a>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
            </section>
        

        </form>

    </div>
{% endblock body %}

products/templates/products/search.html
{% extends 'base.html' %}

{% block title %} | Advanced Search{% endblock%}
{% block body %}
    <div class="my-form container p-5 my-5 rounded border border-warning">
        <form action="{% url 'products:filter' %}">
            <h2 class="text-center">Advanced Search</h2>
            <hr>

            <div class="form-group">
                <label for="inputSearchProductName">Product Name Contains</label>
                <input type="text" class="form-control" name="sname" id="inputSearchProductName" placeholder="espresso">
            </div>
            
            <div class="form-group">
                <label for="inputSearchProductDescription">Product Description Contains</label>
                <input type="text" class="form-control" name="sdescription" id="inputSearchProductDescription" placeholder="coffee">
            </div>

            <div class="form-row">

                <div class="form-group col-md-6">
                    <label for="inputSearchPrice1">Price Between</label>
                    <input type="number" class="form-control" name="sfrom" id="inputSearchPrice1" placeholder="" value="5">
                </div>
    
                <div class="form-group col-md-6">
                    <label for="inputSearchPrice2">And</label>
                    <input type="number" class="form-control" name="sto" id="inputSearchPrice2" placeholder="" value="25">
                </div>

            </div>

            <div class="form-group">
                <div class="pretty p-svg p-curve p-jelly">
                    <input type="checkbox" name="sensitive" id="inputCaseSensitive" />
                    <div class="state p-warning">
                        <!-- svg path -->
                        <svg class="svg svg-icon" viewBox="0 0 20 20">
                            <path d="M7.629,14.566c0.125,0.125,0.291,0.188,0.456,0.188c0.164,0,0.329-0.062,0.456-0.188l8.219-8.221c0.252-0.252,0.252-0.659,0-0.911c-0.252-0.252-0.659-0.252-0.911,0l-7.764,7.763L4.152,9.267c-0.252-0.251-0.66-0.251-0.911,0c-0.252,0.252-0.252,0.66,0,0.911L7.629,14.566z" style="stroke: white;fill:white;"></path>
                        </svg>
                        <label>Case Sensitive</label>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-warning">Search for All</button>
        </form>

    </div>
{% endblock body %}